# Generated by Django 5.1.2 on 2024-10-25 10:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoiceNoType', models.IntegerField(default=0, help_text='Invoice Number Type', max_length=11, verbose_name='Invoice Number Type')),
                ('prefix', models.CharField(help_text='Invoice Prefix', max_length=50, verbose_name='Invoice Prefix')),
                ('notes', models.TextField(help_text='Invoice Notes', null=True, verbose_name='Invoice Notes')),
                ('terms', models.TextField(help_text='Invoice Terms', null=True, verbose_name='Invoice Terms')),
                ('sign', models.ImageField(help_text='Invoice Sign', null=True, upload_to='uploads/invoice/', verbose_name='Invoice Sign')),
                ('logo', models.ImageField(help_text='Invoice Image', null=True, upload_to='uploads/invoice/', verbose_name='Invoice Image')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
