# Generated by Django 5.1.2 on 2024-10-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesetting',
            name='invoiceNoType',
            field=models.IntegerField(default=0, help_text='Invoice Number Type', verbose_name='Invoice Number Type'),
        ),
    ]
