# Generated by Django 5.1.2 on 2024-10-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0002_alter_invoicesetting_invoicenotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesetting',
            name='invoiceNoType',
            field=models.IntegerField(choices=[(1, 'sequence'), (2, 'Random')], default=0, help_text='Invoice Number Type', verbose_name='Invoice Number Type'),
        ),
    ]
