# Generated by Django 5.1 on 2024-11-25 10:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0009_remove_product_len_a_remove_product_len_a_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_upload', models.FileField(blank=True, null=True, upload_to='uploads/videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('invoice_weight', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Weight')),
                ('actual_weight', models.CharField(blank=True, max_length=100, null=True, verbose_name='Actual Weight')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
