# Generated by Django 5.1 on 2024-11-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='len_a',
            field=models.FloatField(blank=True, null=True, verbose_name='Size 1'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='len_a_unit',
            field=models.CharField(choices=[('F', 'Feet'), ('M', 'Meters')], default='feet', max_length=10, verbose_name='Size 1 unit'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='len_b',
            field=models.FloatField(blank=True, null=True, verbose_name='Size 2'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='len_b_unit',
            field=models.CharField(choices=[('F', 'Feet'), ('M', 'Meters')], default='feet', max_length=10, verbose_name='Size 2 unit'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sqft_value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Square feet Value'),
        ),
    ]
