# Generated by Django 5.1 on 2024-11-25 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0002_inventory_len_a_inventory_len_a_unit_inventory_len_b_and_more'),
        ('Product', '0009_remove_product_len_a_remove_product_len_a_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.package', verbose_name='Package Name'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='package_weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Package Weight'),
        ),
    ]
