# Generated by Django 5.1 on 2024-11-25 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0003_inventory_package_inventory_package_weight'),
        ('Product', '0010_rawmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.AddField(
            model_name='inventory',
            name='raw_mat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.rawmaterial', verbose_name='Raw Material'),
        ),
    ]
