# Generated by Django 5.1 on 2024-11-25 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0004_remove_inventory_product_inventory_raw_mat'),
        ('Vendor', '0009_vendor_vendor_codeword'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vendor.vendor', verbose_name='Vendor'),
        ),
    ]
