# Generated by Django 5.1 on 2024-10-21 11:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Client.basemodel')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile')),
                ('bn', models.CharField(blank=True, max_length=15, null=True, verbose_name='Bank Name')),
                ('ahn', models.CharField(blank=True, max_length=15, null=True, verbose_name='Account Holder Name')),
                ('ac_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Account Number')),
                ('ifsc', models.CharField(blank=True, max_length=12, null=True, verbose_name='IFSC Code')),
                ('upi', models.CharField(blank=True, max_length=15, null=True, verbose_name='UPI id')),
                ('cn', models.CharField(blank=True, max_length=256, null=True, verbose_name='Company Name')),
            ],
            bases=('Client.basemodel',),
        ),
    ]
