# Generated by Django 5.1 on 2024-10-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ac_type',
            field=models.CharField(blank=True, choices=[('S', 'Saving'), ('C', 'Current')], null=True, verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='client',
            name='gst',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='GST No'),
        ),
    ]
