# Generated by Django 5.1 on 2024-10-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_client_ac_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ac_type',
            field=models.IntegerField(choices=[(1, 'Saving'), (2, 'Current')], default=1, verbose_name='Account Type'),
        ),
    ]
