# Generated by Django 5.1 on 2024-10-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_alter_client_ac_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gst',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GST No'),
        ),
    ]
