# Generated by Django 5.1 on 2024-11-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_alter_client_address_alter_client_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Client Code'),
        ),
        migrations.AddField(
            model_name='client',
            name='gst_value',
            field=models.FloatField(blank=True, null=True, verbose_name='GST Value'),
        ),
    ]
