# Generated by Django 5.1 on 2024-11-22 13:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vendor', '0008_vendor_gst_value_vendor_vendor_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('po_no', models.IntegerField(blank=True, default=0, null=True, verbose_name='P.O. No')),
                ('po_date', models.DateField(blank=True, null=True, verbose_name='P.O. Date')),
                ('amd_no', models.IntegerField(blank=True, default=0, null=True, verbose_name='Amendment No')),
                ('amd_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('issued_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='Issued By')),
                ('val_start_dat', models.DateField(blank=True, null=True, verbose_name='Validity Start Date')),
                ('val_end_dat', models.DateField(blank=True, null=True, verbose_name='Validity End Date')),
                ('gst_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='GST Registration Number')),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN Number')),
                ('deliver_to', models.TextField(blank=True, null=True, verbose_name='Please Deliver to')),
                ('del_term', models.CharField(blank=True, max_length=150, null=True, verbose_name='Delivery Term')),
                ('pay_term', models.CharField(blank=True, max_length=256, null=True, verbose_name='Payment Term')),
                ('doc_crn', models.CharField(blank=True, max_length=10, null=True, verbose_name='Document Currency')),
                ('sr_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='SNo')),
                ('ic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Item Code / HSN Code')),
                ('des', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order_qty', models.IntegerField(blank=True, default=0, null=True, verbose_name='Order Qty')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unit')),
                ('rate_unit', models.FloatField(blank=True, default=0, null=True, verbose_name='Rate Unit')),
                ('net_value', models.FloatField(blank=True, default=0, null=True, verbose_name='Net Value')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='Vendor.vendor', verbose_name='Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
