# Generated by Django 5.1 on 2024-11-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseOrder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='rate_unit',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Rate Per Unit'),
        ),
    ]
