# Generated by Django 5.1 on 2024-11-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseOrder', '0002_alter_purchaseorder_rate_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='unit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit'),
        ),
    ]
