# Generated by Django 5.1 on 2024-08-28 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mn', models.CharField(max_length=50, verbose_name='Material Name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt', models.CharField(max_length=50, verbose_name='Product Type')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('gauge', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gauge')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Size')),
                ('weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Weight')),
                ('roll', models.CharField(blank=True, max_length=50, null=True, verbose_name='Roll')),
                ('sqft', models.CharField(blank=True, max_length=50, null=True, verbose_name='Square feet')),
                ('sqft_value', models.CharField(blank=True, max_length=50, null=True, verbose_name='Square feet Value')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.material')),
                ('pt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.producttype')),
            ],
        ),
    ]
