# Generated by Django 5.1 on 2024-08-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_material_created_at_material_created_by_material_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sqft',
        ),
        migrations.AddField(
            model_name='product',
            name='len_a',
            field=models.FloatField(blank=True, null=True, verbose_name='Size 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='len_a_unit',
            field=models.CharField(choices=[('feet', 'Feet'), ('meters', 'Meters')], default='feet', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='len_b',
            field=models.FloatField(blank=True, null=True, verbose_name='Size 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='len_b_unit',
            field=models.CharField(choices=[('feet', 'Feet'), ('meters', 'Meters')], default='feet', max_length=10),
        ),
    ]
