# Generated by Django 5.1 on 2024-08-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_remove_product_sqft_product_len_a_product_len_a_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='len_a_unit',
            field=models.CharField(choices=[('feet', 'Feet'), ('meters', 'Meters')], default='feet', max_length=10, verbose_name='Size 1 unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='len_b_unit',
            field=models.CharField(choices=[('feet', 'Feet'), ('meters', 'Meters')], default='feet', max_length=10, verbose_name='Size 1 unit'),
        ),
    ]
