# Generated by Django 5.1 on 2024-08-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_product_len_a_unit_alter_product_len_b_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='len_b_unit',
            field=models.CharField(choices=[('feet', 'Feet'), ('meters', 'Meters')], default='feet', max_length=10, verbose_name='Size 2 unit'),
        ),
    ]
