# Generated by Django 5.1 on 2024-10-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_package_material_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='len_a',
        ),
        migrations.RemoveField(
            model_name='product',
            name='len_a_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='len_b',
        ),
        migrations.RemoveField(
            model_name='product',
            name='len_b_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sqft_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
