# Generated by Django 5.1 on 2024-11-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_rawmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='package',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Weight'),
        ),
    ]
